# Asterisk ARA Router Production Configuration

app:
  name: asterisk-ara-router
  version: 2.0.0
  environment: production
  debug: true

database:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: temppass
  database: asterisk_ara
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 5m
  retry_attempts: 3
  retry_delay: 1s
  charset: utf8mb4

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 20
  min_idle_conns: 5
  max_retries: 3
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_timeout: 4s
  idle_timeout: 5m

agi:
  listen_address: 0.0.0.0
  port: 4573
  max_connections: 1000
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s
  shutdown_timeout: 30s
  buffer_size: 4096
  enable_tls: false

asterisk:
  ami:
    enabled: true
    host: localhost
    port: 5038
    username: routerami
    password: routerpass
    reconnect_interval: 5s
    ping_interval: 30s
    action_timeout: 10s
    connect_timeout: 10s
    event_buffer_size: 1000
  ara:
    transport_reload_interval: 60s
    endpoint_cache_ttl: 300s
    dialplan_cache_ttl: 600s
    aor_cache_ttl: 300s
    auth_cache_ttl: 300s
    enable_cache: true
    sync_interval: 60s

router:
  did_allocation_timeout: 5s
  call_cleanup_interval: 5m
  stale_call_timeout: 30m
  max_retries: 3
  retry_backoff: exponential
  verification:
    enabled: true
    strict_mode: false
    log_failures: true
    timeout: 5s
  recording:
    enabled: true
    path: /var/spool/asterisk/monitor
    format: wav
    mix_type: both
    max_size: 0
    max_age: 30
  load_balancer:
    default_mode: round_robin
    health_check_interval: 30s
    failover_timeout: 5s
    max_failures: 3
    recovery_time: 5m

monitoring:
  metrics:
    enabled: true
    port: 9090
    path: /metrics
    namespace: ara_router
    subsystem: ""
    collect_interval: 10s
  health:
    enabled: true
    port: 8080
    liveness_path: /health/live
    readiness_path: /health/ready
    check_interval: 30s
    check_timeout: 5s
  logging:
    level: info
    format: json
    output: stdout
    file:
      enabled: true
      path: /var/log/asterisk/ara-router.log
      max_size: 100
      max_backups: 5
      max_age: 30
      compress: true
    fields:
      service: ara-router
      environment: production
  tracing:
    enabled: false
    provider: jaeger
    endpoint: http://localhost:14268/api/traces
    service_name: ara-router
    sample_rate: 0.1

security:
  tls:
    enabled: false
    cert_file: ""
    key_file: ""
    ca_file: ""
    insecure_skip_verify: false
    min_version: "1.2"
    cipher_suites: []
  api:
    enabled: true
    port: 8081
    auth_token: ""
    rate_limit: 100
    cors_enabled: true
    cors_origins:
      - "*"
    read_timeout: 30s
    write_timeout: 30s
  rate_limit:
    enabled: true
    requests_per_min: 1000
    burst_size: 100
    cleanup_interval: 1m

performance:
  worker_pool_size: 100
  queue_size: 1000
  batch_size: 50
  gc_interval: 1m
  max_procs: 0
  enable_profiling: false
  profiling_port: 6060
